### PR TITLE
Font combo three: Nunito and OpenSans

### PR DESCRIPTION
**Pull request by travishathaway**
This is one potential option for a font pairing for conda.org. I have also added some CSS updates for the for the front page.

@Asmit2952

### CODE REVIEW

**Review by Asmit2952 — COMMENTED** [review]
Can we have a community vote on this? I think #69 and #64 are good to go in my opinion.

**Comment by jezdez** [comment]
I prefer this over #64

**Comment by travishathaway** [comment]
@Asmit2952, I'll bring this up in our Element/Matrix chat.

**Comment by travishathaway** [comment]
I am going to merge this for now considering we have several pro votes.

**Comment by travishathaway** [comment]
I'm going to have an official vote on our font choice next team meeting, but so far it looks like this is the one.

**Pull request merged**
