### PR TITLE
Moved news items from /news to /blog

### PR DESCRIPTION
**Pull request by tnabtaf**
We are placing all news/blog items in the /blog directory, which is natively supported by Docusaurus.

This commit includes blog post with an external_url in the metadata.  That is not currently supported, and we'll need to either support it, or update blog post to include text and a link to the original item.

### CODE REVIEW

**Comment by tnabtaf** [comment]
Just a reminder that this still needs a reveiw.

**Comment by tnabtaf** [comment]
Weird.  I swear this had already been merged....

**Comment by Asmit2952** [comment]
Hey @tnabtaf the blogs look good to me. They seem to render perfectly on the page. Sorry for reviewing it late.

**Comment by tnabtaf** [comment]
Thanks @Asmit2952 .  Can you do a formal github review?  I can't merge this until that happens.

**Review by Asmit2952 — APPROVED** [review]
Hey @tnabtaf this looks good to me. I think now you can merge it?

**Comment by tnabtaf** [comment]
Yes!  Thank you @Asmit2952 !

**Pull request merged**
