### PR TITLE
FAQ - Why should I use conda?

### PR DESCRIPTION
**Pull request by Shreyas-SAS**
Added a comparison of conda with other alternatives highlighting its pros to convince users to choose conda over other.

### CODE REVIEW

**Review by kathatherine — COMMENTED** [review]
So I'm unsure if this is the direction we want to go in for this question. This feels like a marketing blurb and while I think it's good to inform users about what conda is capable of, It's probably better to come at it from the direction of what they're trying to accomplish. Why conda over pip, for instance? How is conda useful for different kinds of work? @jaimergp, if I remember correctly, you were interested in this question being added. Do you have any idea of what you were wanting to see here?

**Comment by Shreyas-SAS** [comment]
> So I'm unsure if this is the direction we want to go in for this question. This feels like a marketing blurb and while I think it's good to inform users about what conda is capable of, It's probably better to come at it from the direction of what they're trying to accomplish. Why conda over pip, for instance? How is conda useful for different kinds of work? @jaimergp, if I remember correctly, you were interested in this question being added. Do you have any idea of what you were wanting to see here?

Oh, should I edit it then? I felt that it wouldn't be good if we try to show that conda is better than some other software while naming them thus decided to highlight the plus points of using conda over comparing it with other similar products like pip or other similar competitors.

**Comment by Shreyas-SAS** [comment]
@kathatherine please view the changes if they are fin now. I still highlighted plus points of using conda, if you wish I will add as objective analysis of conda vs pip env. Thanks.

**Comment by Shreyas-SAS** [comment]
Hey @kathatherine, I will close this PR since it's completed by Pinak for GSOD. Thanks for the opportunity though.

**Comment by kathatherine** [comment]
Thank you, @Shreyas-SAS!

**Pull request closed without merging**
